//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXwebReportViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public int IdPais { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string IsoA2 { get; set; }
        public string Capital { get; set; }
        public bool EstadoActivo { get; set; }
    }
}
